// src/pages/Home.tsx
import React from 'react';
import { Box, Typography, Button, Grid, Card, CardContent } from '@mui/material';
import { motion } from 'framer-motion';
import { Ruler, Users, Clock } from 'lucide-react';

const Home = () => {
  return (
    <Box>
      <Box
        sx={{
          textAlign: 'center',
          mb: 8,
          mt: 4,
        }}
        component={motion.div}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <Typography variant="h1" gutterBottom>
          Custom Tailoring, Simplified
        </Typography>
        <Typography variant="h5" color="text.secondary" sx={{ mb: 4 }}>
          Get perfectly fitted garments from expert tailors, all from the comfort of your home
        </Typography>
        <Button variant="contained" size="large" color="primary" sx={{ mr: 2 }}>
          Get Started
        </Button>
        <Button variant="outlined" size="large">
          Learn More
        </Button>
      </Box>

      <Grid container spacing={4}>
        {[
          {
            icon: <Ruler size={32} />,
            title: 'Easy Measurements',
            description: 'Follow our guided measurement process with video tutorials',
          },
          {
            icon: <Users size={32} />,
            title: 'Expert Tailors',
            description: 'Connect with skilled tailors and view their portfolios',
          },
          {
            icon: <Clock size={32} />,
            title: 'Quick Turnaround',
            description: 'Get your custom garments delivered within 2-3 weeks',
          },
        ].map((feature, index) => (
          <Grid item xs={12} md={4} key={index}>
            <Card
              component={motion.div}
              whileHover={{ y: -5 }}
              sx={{ height: '100%' }}
            >
              <CardContent sx={{ textAlign: 'center' }}>
                <Box sx={{ color: 'primary.main', mb: 2 }}>{feature.icon}</Box>
                <Typography variant="h6" gutterBottom>
                  {feature.title}
                </Typography>
                <Typography color="text.secondary">
                  {feature.description}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>
    </Box>
  );
};

export default Home;

// src/views/Home.vue
<template>
  <div class="container mx-auto px-4 py-12">
    <div class="text-center mb-16">
      <h1 class="text-4xl md:text-5xl font-bold mb-6 text-[#2C3E50]">
        Custom Tailoring, Simplified
      </h1>
      <p class="text-xl text-gray-600 mb-8">
        Get perfectly fitted garments from expert tailors, all from the comfort of your home
      </p>
      <div class="flex flex-wrap justify-center gap-4">
        <el-button type="primary" size="large">
          Get Started
        </el-button>
        <el-button size="large">
          Learn More
        </el-button>
      </div>
    </div>

    <el-row :gutter="24" class="features">
      <el-col 
        v-for="feature in features" 
        :key="feature.title"
        :xs="24"
        :sm="24"
        :md="8"
      >
        <el-card 
          class="feature-card h-full"
          :body-style="{ padding: '2rem' }"
        >
          <div class="text-center">
            <component 
              :is="feature.icon" 
              class="text-[#2ecc71] mb-4"
              :size="32"
            />
            <h3 class="text-xl font-bold mb-2">{{ feature.title }}</h3>
            <p class="text-gray-600">{{ feature.description }}</p>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { RulerIcon, UsersIcon, ClockIcon } from 'lucide-vue-next'

const features = [
  {
    icon: RulerIcon,
    title: 'Easy Measurements',
    description: 'Follow our guided measurement process with video tutorials'
  },
  {
    icon: UsersIcon,
    title: 'Expert Tailors',
    description: 'Connect with skilled tailors and view their portfolios'
  },
  {
    icon: ClockIcon,
    title: 'Quick Turnaround',
    description: 'Get your custom garments delivered within 2-3 weeks'
  }
]
</script>

<style scoped>
.feature-card {
  transition: transform 0.3s ease;
}

.feature-card:hover {
  transform: translateY(-5px);
}
</style>
