// src/components/AppFooter.tsx
import React from 'react';
import { 
  Box, 
  Container, 
  Typography, 
  Grid, 
  Link, 
  Divider, 
  IconButton 
} from '@mui/material';
import { 
  Facebook, 
  Twitter, 
  Instagram, 
  Mail, 
  MapPin, 
  Phone 
} from 'lucide-react';
import { Link as RouterLink } from 'react-router-dom';

const AppFooter: React.FC = () => {
  const currentYear = new Date().getFullYear();

  const quickLinks = [
    { text: 'Home', path: '/' },
    { text: 'Measurements', path: '/measurements' },
    { text: 'Find Tailors', path: '/tailors' },
    { text: 'About Us', path: '/about' },
    { text: 'Login', path: '/login' }
  ];

  const services = [
    'Custom Tailoring',
    'Alterations',
    'Wedding Attire',
    'Corporate Uniforms',
    'Style Consultation'
  ];

  return (
    <Box 
      component="footer" 
      sx={{ 
        bgcolor: 'primary.main', 
        color: 'white',
        py: 6
      }}
    >
      <Container maxWidth="lg">
        <Grid container spacing={4}>
          <Grid item xs={12} md={4}>
            <Box sx={{ mb: 3 }}>
              <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 2 }}>
                Seamless
              </Typography>
              <Typography variant="body2" sx={{ mb: 2, opacity: 0.8 }}>
                Revolutionizing the tailoring industry through technology and connecting customers with expert tailors worldwide.
              </Typography>
              <Box sx={{ display: 'flex', gap: 1 }}>
                <IconButton color="inherit" size="small">
                  <Facebook size={20} />
                </IconButton>
                <IconButton color="inherit" size="small">
                  <Twitter size={20} />
                </IconButton>
                <IconButton color="inherit" size="small">
                  <Instagram size={20} />
                </IconButton>
              </Box>
            </Box>
          </Grid>

          <Grid item xs={12} sm={6} md={2}>
            <Typography variant="h6" sx={{ mb: 2 }}>
              Quick Links
            </Typography>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              {quickLinks.map((link) => (
                <Link
                  key={link.text}
                  component={RouterLink}
                  to={link.path}
                  sx={{
                    color: 'white',
                    opacity: 0.8,
                    textDecoration: 'none',
                    '&:hover': {
                      opacity: 1,
                      textDecoration: 'none',
                    },
                  }}
                >
                  {link.text}
                </Link>
              ))}
            </Box>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Typography variant="h6" sx={{ mb: 2 }}>
              Services
            </Typography>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              {services.map((service) => (
                <Typography
                  key={service}
                  variant="body2"
                  sx={{ opacity: 0.8 }}
                >
                  {service}
                </Typography>
              ))}
            </Box>
          </Grid>

          <Grid item xs={12} md={3}>
            <Typography variant="h6" sx={{ mb: 2 }}>
              Contact Us
            </Typography>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <MapPin size={18} />
                <Typography variant="body2" sx={{ opacity: 0.8 }}>
                  123 Fashion Street, Design District
                </Typography>
              </Box>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <Phone size={18} />
                <Typography variant="body2" sx={{ opacity: 0.8 }}>
                  +1 (555) 123-4567
                </Typography>
              </Box>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <Mail size={18} />
                <Typography variant="body2" sx={{ opacity: 0.8 }}>
                  contact@seamless.com
                </Typography>
              </Box>
            </Box>
          </Grid>
        </Grid>

        <Divider sx={{ my: 4, borderColor: 'rgba(255, 255, 255, 0.1)' }} />

        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 2 }}>
          <Typography variant="body2" sx={{ opacity: 0.8 }}>
            © {currentYear} Seamless. All rights reserved.
          </Typography>
          <Box sx={{ display: 'flex', gap: 3 }}>
            {['Privacy Policy', 'Terms of Service', 'Cookie Policy'].map((text) => (
              <Link
                key={text}
                href="#"
                sx={{
                  color: 'white',
                  opacity: 0.8,
                  textDecoration: 'none',
                  '&:hover': {
                    opacity: 1,
                    textDecoration: 'underline',
                  },
                }}
              >
                {text}
              </Link>
            ))}
          </Box>
        </Box>
      </Container>
    </Box>
  );
};

export default AppFooter;

// src/components/AppFooter.vue
<template>
  <footer class="bg-primary text-white py-12">
    <div class="container mx-auto px-4">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        <div>
          <h3 class="text-xl font-bold mb-4 flex items-center gap-2">
            <scissors-icon :size="24" class="text-highlight" />
            Seamless
          </h3>
          <p class="text-sm text-secondary/80 mb-6">
            Revolutionizing the tailoring industry through technology and connecting customers with expert tailors worldwide.
          </p>
          <div class="flex gap-4">
            <a 
              v-for="icon in socialIcons"
              :key="icon.name"
              :href="icon.link"
              target="_blank"
              rel="noopener noreferrer"
              class="group"
            >
              <el-button 
                circle
                class="social-btn !bg-primary-light hover:!bg-highlight hover:!text-primary transition-all duration-300 transform group-hover:scale-110"
              >
                <component :is="icon.component" :size="18" />
              </el-button>
            </a>
          </div>
        </div>

        <div>
          <h4 class="font-bold mb-4">Quick Links</h4>
          <div class="flex flex-col gap-2">
            <router-link 
              v-for="link in quickLinks"
              :key="link.path"
              :to="link.path"
              class="text-sm text-secondary/80 hover:text-highlight transition-colors flex items-center gap-2"
            >
              <component :is="link.icon" :size="16" />
              {{ link.label }}
            </router-link>
          </div>
        </div>

        <div>
          <h4 class="font-bold mb-4">Services</h4>
          <div class="flex flex-col gap-2">
            <span 
              v-for="service in services"
              :key="service.label"
              class="text-sm text-secondary/80 flex items-center gap-2"
            >
              <component :is="service.icon" :size="16" class="text-highlight" />
              {{ service.label }}
            </span>
          </div>
        </div>

        <div>
          <h4 class="font-bold mb-4">Contact Us</h4>
          <div class="flex flex-col gap-4">
            <div v-for="contact in contactInfo" :key="contact.label" class="flex items-center gap-2">
              <component :is="contact.icon" :size="18" class="text-highlight" />
              <span class="text-sm text-secondary/80">{{ contact.label }}</span>
            </div>
          </div>
        </div>
      </div>

      <div class="mt-12 pt-8 border-t border-white/10 flex flex-col md:flex-row justify-between gap-4">
        <p class="text-sm text-secondary/80">
          © {{ new Date().getFullYear() }} Seamless. All rights reserved.
        </p>
        <div class="flex gap-6">
          <a 
            v-for="link in legalLinks"
            :key="link"
            href="#"
            class="text-sm text-secondary/80 hover:text-highlight transition-colors"
          >
            {{ link }}
          </a>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { 
  ScissorsIcon, 
  FacebookIcon, 
  TwitterIcon, 
  InstagramIcon,
  LinkedinIcon,
  MapPinIcon,
  PhoneIcon,
  MailIcon,
  HomeIcon,
  RulerIcon,
  UsersIcon,
  InfoIcon,
  ScissorsSquareIcon,
  ShirtIcon,
  HeartIcon,
  BuildingIcon
} from 'lucide-vue-next'

const socialIcons = [
  { 
    name: 'facebook', 
    component: FacebookIcon,
    link: 'https://facebook.com'
  },
  { 
    name: 'twitter', 
    component: TwitterIcon,
    link: 'https://twitter.com'
  },
  { 
    name: 'instagram', 
    component: InstagramIcon,
    link: 'https://instagram.com'
  },
  { 
    name: 'linkedin', 
    component: LinkedinIcon,
    link: 'https://linkedin.com'
  }
]

const quickLinks = [
  { label: 'Home', path: '/', icon: HomeIcon },
  { label: 'Measurements', path: '/measurements', icon: RulerIcon },
  { label: 'Find Tailors', path: '/tailors', icon: UsersIcon },
  { label: 'About Us', path: '/about', icon: InfoIcon }
]

const services = [
  { label: 'Custom Tailoring', icon: ScissorsSquareIcon },
  { label: 'Alterations', icon: ShirtIcon },
  { label: 'Wedding Attire', icon: HeartIcon },
  { label: 'Corporate Uniforms', icon: BuildingIcon }
]

const contactInfo = [
  { icon: MapPinIcon, label: 'Kenyatta Avenue, Nakuru West' },
  { icon: PhoneIcon, label: '+254 713593401' },
  { icon: MailIcon, label: 'contact@seamless.com' }
]

const legalLinks = [
  'Privacy Policy',
  'Terms of Service',
  'Cookie Policy'
]
</script>

<style scoped>
.social-btn {
  position: relative;
  overflow: hidden;
}

.social-btn::after {
  content: '';
  position: absolute;
  top: 50%;
  left: 50%;
  width: 0;
  height: 0;
  background: rgba(255, 255, 255, 0.2);
  border-radius: 50%;
  transform: translate(-50%, -50%);
  transition: width 0.3s, height 0.3s;
}

.social-btn:hover::after {
  width: 100%;
  height: 100%;
}
</style>
