// src/components/NavBar.tsx
import React, { useState } from 'react';
import { 
  AppBar, 
  Toolbar, 
  Typography, 
  Button, 
  Container, 
  Box, 
  Drawer, 
  List, 
  ListItem, 
  ListItemIcon, 
  ListItemText, 
  useMediaQuery, 
  useTheme 
} from '@mui/material';
import { 
  Scissors, 
  Menu, 
  Home, 
  Ruler, 
  Users, 
  Info 
} from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

const NavBar: React.FC = () => {
  const navigate = useNavigate();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('lg'));
  const [drawerOpen, setDrawerOpen] = useState(false);

  const menuItems = [
    { 
      label: 'Home', 
      path: '/',
      icon: Home
    },
    { 
      label: 'Measurements', 
      path: '/measurements',
      icon: Ruler
    },
    { 
      label: 'Find Tailors', 
      path: '/tailors',
      icon: Users
    },
    { 
      label: 'About Us', 
      path: '/about',
      icon: Info
    }
  ];

  const toggleDrawer = (open: boolean) => (event: React.KeyboardEvent | React.MouseEvent) => {
    if (
      event.type === 'keydown' &&
      ((event as React.KeyboardEvent).key === 'Tab' ||
        (event as React.KeyboardEvent).key === 'Shift')
    ) {
      return;
    }
    setDrawerOpen(open);
  };

  return (
    <AppBar 
      position="sticky" 
      color="default" 
      elevation={0}
      sx={{ 
        borderBottom: '1px solid #BDC3C7',
        backgroundColor: 'background.paper',
        zIndex: theme.zIndex.drawer + 1
      }}
    >
      <Container maxWidth="lg">
        <Toolbar disableGutters sx={{ height: 64 }}>
          <Box 
            component={Link} 
            to="/"
            sx={{ 
              display: 'flex', 
              alignItems: 'center', 
              gap: 1,
              textDecoration: 'none',
              color: 'primary.main',
              fontWeight: 700,
              '&:hover .logo-icon': {
                transform: 'rotate(45deg)',
                color: 'secondary.main'
              },
              '&:hover .logo-text': {
                color: 'secondary.main'
              }
            }}
          >
            <Scissors 
              className="logo-icon"
              size={24} 
              color="#E74C3C" 
              style={{ 
                transition: 'transform 0.3s ease, color 0.3s ease'
              }} 
            />
            <Typography 
              variant="h6" 
              className="logo-text"
              sx={{ 
                transition: 'color 0.3s ease'
              }}
            >
              Seamless
            </Typography>
          </Box>

          {!isMobile && (
            <>
              <Box sx={{ display: 'flex', ml: 8, gap: 4 }}>
                {menuItems.map((item) => (
                  <Box
                    key={item.path}
                    component={Link}
                    to={item.path}
                    sx={{
                      position: 'relative',
                      color: 'text.secondary',
                      textDecoration: 'none',
                      py: 2,
                      '&:hover': {
                        color: 'primary.main'
                      },
                      '&:hover::after': {
                        width: '100%'
                      },
                      '&::after': {
                        content: '""',
                        position: 'absolute',
                        bottom: 0,
                        left: 0,
                        width: 0,
                        height: '2px',
                        backgroundColor: 'secondary.main',
                        transition: 'width 0.3s ease'
                      }
                    }}
                  >
                    {item.label}
                  </Box>
                ))}
              </Box>

              <Box sx={{ ml: 'auto', display: 'flex', gap: 2 }}>
                <Button 
                  variant="outlined" 
                  onClick={() => navigate('/login')}
                  sx={{
                    '&:hover': {
                      borderColor: 'secondary.main',
                      color: 'secondary.main'
                    }
                  }}
                >
                  Sign In
                </Button>
                <Button 
                  variant="contained" 
                  color="primary"
                  onClick={() => navigate('/register')}
                  sx={{
                    '&:hover': {
                      backgroundColor: 'primary.light'
                    }
                  }}
                >
                  Get Started
                </Button>
              </Box>
            </>
          )}

          {isMobile && (
            <Box sx={{ ml: 'auto' }}>
              <Button 
                onClick={toggleDrawer(true)}
                sx={{ minWidth: 'auto', p: 1 }}
              >
                <Menu size={24} color={theme.palette.primary.main} />
              </Button>
            </Box>
          )}
        </Toolbar>
      </Container>

      <Drawer
        anchor="right"
        open={drawerOpen}
        onClose={toggleDrawer(false)}
        sx={{
          '& .MuiDrawer-paper': {
            width: '80%',
            maxWidth: '300px'
          }
        }}
      >
        <Box sx={{ p: 2, borderBottom: '1px solid', borderColor: 'divider', display: 'flex', alignItems: 'center', gap: 1 }}>
          <Scissors size={24} color="#E74C3C" />
          <Typography variant="h6" color="primary" fontWeight={700}>
            Seamless
          </Typography>
        </Box>
        
        <List sx={{ p: 2 }}>
          {menuItems.map((item) => (
            <ListItem 
              button 
              key={item.path}
              onClick={() => {
                navigate(item.path);
                setDrawerOpen(false);
              }}
              sx={{ py: 1.5 }}
            >
              <ListItemIcon sx={{ minWidth: 40 }}>
                <item.icon size={20} />
              </ListItemIcon>
              <ListItemText primary={item.label} />
            </ListItem>
          ))}
          
          <Box sx={{ mt: 4, pt: 2, borderTop: '1px solid', borderColor: 'divider', display: 'flex', flexDirection: 'column', gap: 2 }}>
            <Button 
              variant="outlined" 
              fullWidth
              onClick={() => {
                navigate('/login');
                setDrawerOpen(false);
              }}
            >
              Sign In
            </Button>
            <Button 
              variant="contained" 
              color="primary"
              fullWidth
              onClick={() => {
                navigate('/register');
                setDrawerOpen(false);
              }}
            >
              Get Started
            </Button>
          </Box>
        </List>
      </Drawer>
    </AppBar>
  );
};

export default NavBar;

// src/components/NavBar.vue
<template>
  <el-header class="bg-surface border-b border-[#BDC3C7] shadow-sm sticky top-0 z-50">
    <div class="container mx-auto px-4">
      <div class="h-16 flex items-center justify-between">
        <router-link to="/" class="flex items-center gap-2 text-xl font-bold text-primary group">
          <scissors-icon :size="24" class="text-accent transform group-hover:rotate-45 transition-transform duration-300" />
          <span class="group-hover:text-accent transition-colors">Seamless</span>
        </router-link>

        <div class="hidden lg:flex items-center gap-8">
          <router-link 
            v-for="item in menuItems" 
            :key="item.path"
            :to="item.path"
            class="relative text-text-muted hover:text-primary transition-colors py-2 group"
          >
            {{ item.label }}
            <span class="absolute bottom-0 left-0 w-0 h-0.5 bg-accent group-hover:w-full transition-all duration-300"></span>
          </router-link>
          
          <div class="flex items-center gap-4">
            <el-button 
              plain
              @click="$router.push('/login')"
              class="hover:border-accent hover:text-accent transition-colors"
            >
              Sign In
            </el-button>
            <el-button 
              type="primary" 
              @click="$router.push('/register')"
              class="bg-primary hover:bg-primary-light transition-colors"
            >
              Get Started
            </el-button>
          </div>
        </div>

        <el-button 
          class="lg:hidden"
          @click="drawer = true"
          text
        >
          <menu-icon class="text-primary hover:text-accent transition-colors" :size="24" />
        </el-button>
      </div>
    </div>

    <el-drawer
      v-model="drawer"
      direction="rtl"
      size="80%"
      class="mobile-menu"
    >
      <template #header>
        <div class="flex items-center gap-2">
          <scissors-icon :size="24" class="text-accent" />
          <span class="text-xl font-bold text-primary">Seamless</span>
        </div>
      </template>

      <div class="flex flex-col gap-6 p-4">
        <router-link 
          v-for="item in menuItems" 
          :key="item.path"
          :to="item.path"
          class="text-text-muted hover:text-primary py-2 transition-colors flex items-center gap-2"
          @click="drawer = false"
        >
          <component :is="item.icon" :size="20" />
          {{ item.label }}
        </router-link>
        
        <div class="flex flex-col gap-4 mt-4 pt-4 border-t border-gray-200">
          <el-button 
            plain
            @click="$router.push('/login')"
            class="w-full justify-center"
          >
            Sign In
          </el-button>
          <el-button 
            type="primary" 
            @click="$router.push('/register')"
            class="w-full justify-center"
          >
            Get Started
          </el-button>
        </div>
      </div>
    </el-drawer>
  </el-header>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { 
  ScissorsIcon, 
  MenuIcon, 
  HomeIcon,
  RulerIcon,
  UsersIcon,
  InfoIcon
} from 'lucide-vue-next'

const drawer = ref(false)

const menuItems = [
  { 
    label: 'Home', 
    path: '/',
    icon: HomeIcon
  },
  { 
    label: 'Measurements', 
    path: '/measurements',
    icon: RulerIcon
  },
  { 
    label: 'Find Tailors', 
    path: '/tailors',
    icon: UsersIcon
  },
  { 
    label: 'About Us', 
    path: '/about',
    icon: InfoIcon
  }
]
</script>

<style scoped>
.mobile-menu :deep(.el-drawer__header) {
  margin-bottom: 0;
  padding: 16px 20px;
  border-bottom: 1px solid var(--el-border-color);
}

.mobile-menu :deep(.el-drawer__body) {
  padding: 0;
}
</style>
